apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "devsecops"
        vault.hashicorp.com/agent-inject-secret-redis-password.txt: "secret/redis-cart/config"      
        # vault.hashicorp.com/agent-inject-template-redis-password: |
        #   {{- with secret "secret/redis-cart/config" -}}
        #   export REDIS_PASSWORD="{{ .Data.data.password }}"
        #   {{- end -}}          
    spec:
      serviceAccountName: redis-cart
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
      - name: harbor-cred
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: harbor.creativebox.dev/devsecops/cartservice:17
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        # - name: REDIS_PASSWORD
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: spec.containers[0].env[1].value
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 15
          grpc:
            port: 7070
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          grpc:
            port: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
